# permissions for end users to edit accessrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessrequest-editor-role
rules:
- apiGroups:
  - cr.requests.test
  resources:
  - accessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cr.requests.test
  resources:
  - accessrequests/status
  verbs:
  - get
  - patch
  - update
